### ISSUE TITLE
Component generator

### ISSUE THREAD

**Issue by himdel** [ManageIQ/ui-components#120]
@skateman suggested we should have a script to generate a new empty component with all the boilerplate needed .. sounds like a good idea :).

I'm guessing http://yeoman.io/?

(Mostly creating this issue so that I don't forget, but if anyone wants to take this.. :) )

**Comment by chalettu** [comment]
I am all for yeoman generators.  I have built them in the past.  Do you have a notion of what things you want in your template?

**Comment by himdel** [comment]
@chalettu Thanks, that's good news :)

I think mostly what we have there right now anyway.. it should..

* create a component
* all the missing `index.ts` files that just require and register stuff along the way
* create the demo screen for that component
* adds the module to application-settings.js

**Comment by skateman** [comment]
yay
