### ISSUE TITLE
Add "required" field indicator on dialog-user component

### ISSUE THREAD

**Issue by chriskacerguis** [ManageIQ/ui-components#154]
When a Dialog Element is set Required = True, we should show an information in the Dialog. I thought we were putting a “*” but discovered this is not the case. User will find out when clicking submit….. I think this is a pretty simple and will help a lot.

**Comment by chriskacerguis** [comment]
Per @serenamarie125 

![unnamed](https://user-images.githubusercontent.com/2414647/30331245-4576b1c6-97a5-11e7-89e3-c9bf4ff30d92.png)

**Comment by h-kataria** [comment]
Closing, This has already been implemented
![Screenshot from 2020-06-30 11-29-21](https://user-images.githubusercontent.com/3450808/86145509-009f8780-bac5-11ea-8522-dec691129b16.png)
