### ISSUE TITLE
Separate GTL item

### ISSUE THREAD

**Issue by karelhala** [ManageIQ/ui-components#160]
Right now we have GTL view which includes pagination and GTL item directly, it would be nice to have component just for each GTL object (small/big tile, table). This way we could use this (any GTL item) component wherever we want without pagination.

EDIT: Also this might be interesting to UX team as well. Since we will be working with tables and refactoring them, how about we unify the styles and discuss what exactly is needed for each type of view.
Basically I think we have 2 questions.
1) Which types do we want?
Grid is fine I guess, however what about tiles and table? I remember that we wanted to change this to something else, perhaps [list-view](http://www.patternfly.org/pattern-library/content-views/list-view/)?
2) Are we happy with how Grid looks like? Are there any things that can be improved?

This issue might be broken apart a couple of PRs, it's just to start discussion and to move forward something more usable and UX friendly.

**Comment by karelhala** [comment]
ping @AparnaKarve @serenamarie125 @martinpovolny @epwinchell

**Comment by epwinchell** [comment]
We've had discussions with @serenamarie125 in the past about replacing Tile View with PF ListView. I'm strongly in favor of that.

cc\ @dclarizio
