### ISSUE TITLE
Dialogs and required checkboxes

### ISSUE THREAD

**Issue by chalettu** [ManageIQ/ui-components#178]
Per @Loicavenel we expect when a checkbox is "required", that means that it needs to validate as being checked. Any other state should produce an error.

**Comment by h-kataria** [comment]
Closing, already implemented

![Screenshot from 2020-06-30 11-33-32](https://user-images.githubusercontent.com/3450808/86145949-93402680-bac5-11ea-929a-d665f89c830d.png)
