### ISSUE TITLE
Dialog field regex not validating

### ISSUE THREAD

**Issue by chalettu** [ManageIQ/ui-components#180]
When testing with the regex string  \A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z
the API returns ```\\A[\\w+\\-.]+@[a-z\\d\\-]+(\\.[a-z]+)*\\.[a-z]+\\z```  I think the escaped ```\\``` is causing our regex validation to not work.  Investigate issue and fix.

**Comment by h-kataria** [comment]
closing, already implemented
![Screenshot from 2020-06-30 11-38-36](https://user-images.githubusercontent.com/3450808/86146502-4e68bf80-bac6-11ea-9c7d-1447bd07daea.png)

![Screenshot from 2020-06-30 11-38-19](https://user-images.githubusercontent.com/3450808/86146510-51fc4680-bac6-11ea-9f9a-2e6f219cbf22.png)
