### ISSUE TITLE
Quadicon component

### ISSUE THREAD

**Issue by karelhala** [ManageIQ/ui-components#222]
We are lacking quadicon component, right now it's generated on server and rendered as HTML object inside grid or tile.

### Improvements
Click action is now really complex and inside of it it's calculated what screen and what action should be triggered.
We could use more complex actions and show more information based on each quadicon.

**Comment by martinpovolny** [comment]
WIP is here: https://github.com/ManageIQ/ui-components/pull/175

**Comment by skateman** [comment]
@miq-bot assign @skateman
