### ISSUE TITLE
Toolbar hasContent true when it should be falsy

### ISSUE THREAD

**Issue by himdel** [ManageIQ/ui-components#23]
I'm seeing a case where the `miq-toolbar-group` is generated (`vm.hasContent(item) returns true`) but not shown because it's empty..

To the left of the Configuration button..

![foreman-toolbar](https://cloud.githubusercontent.com/assets/289743/18592356/246ecf18-7c26-11e6-99c9-8d5a252088f7.png)

This is the toolbarItem value: 

```json
[{"id":"history_choice","type":"buttonSelect","img":"history_choice.png","imgdis":"history_choice.png","icon":"fa fa-arrow-left fa-lg","name":"history_choice","hidden":false,"pressed":null,"onwhen":null,"data":null,"enabled":false,"title":"History","items":[],"explorer":true,"$$hashKey":"object:171"}]
```

Pretty sure the group should be hidden if empty, so hasContent should return false in this case.

@karelhala can you look into it please or should I?

**Comment by karelhala** [comment]
I'll look into it.

**Comment by karelhala** [comment]
Btw good catch, and great steps to reproduce. Took me about 10 minutes to fix it.
