### ISSUE TITLE
Cannot set property 'hidden' of undefined while hiding a button

### ISSUE THREAD

**Issue by himdel** [ManageIQ/ui-components#26]
https://files.gitter.im/PanSpagetka/3npj/Screenshot-from-2016-09-20-10-33-05.png

Happens during 

```
ManageIQ.toolbars.hideItem('#center_tb', 'perf_refresh');
ManageIQ.toolbars.hideItem('#center_tb', 'perf_reload');
```

in VM's Utilization screen.

@karelhala the usual question :) (I have not yet tried to figure out if this is because the button didn't exist or something like that, but we should probably not crash anyway..)

**Comment by karelhala** [comment]
Yeah, looks like the problem is that this button does not exists, I have a fix prepared, I just want to create test case for this as well.

**Comment by karelhala** [comment]
This issue is relevant to main repo.

**Comment by himdel** [comment]
@PanSpagetka ..should be fixed now, can you verify?

**Comment by PanSpagetka** [comment]
@himdel  @karelhala thanks :+1: seems to be ok :)
