### ISSUE TITLE
Dynamic dialog radio button styling issue

### ISSUE THREAD

**Issue by epwinchell** [ManageIQ/ui-components#330]
As mentioned in: https://github.com/ManageIQ/ui-components/pull/318 , the styling of radio buttons in the dynamic dialog is non-standard (radio buttons  wrapped in a label with "btn btn-primary" classes applied)

<img width="285" alt="screen shot 2018-07-23 at 3 59 37 pm" src="https://user-images.githubusercontent.com/1287144/43099839-6e27ca72-8e91-11e8-9c99-39b1aeb7beeb.png">

vs 

<img width="280" alt="screen shot 2018-07-23 at 4 02 54 pm" src="https://user-images.githubusercontent.com/1287144/43099969-e4ddbff0-8e91-11e8-9db7-9ed45dddb837.png">

@chalettu @eclarizio Any idea what the rationale might have been for styling them that way? Do you see any issues with changing it from the SUI perspective?

cc\ @Rohoover @terezanovotna @Loicavenel

**Comment by epwinchell** [comment]
@miq-bot assign @epwinchell

**Comment by chalettu** [comment]
This particular style issue predates me here on the Service UI team.  I believe it predates patternfly's styling as well.  Truthfully, I don't think there is anyone here that can probably provide the rational behind why it was chosen to style them this way.  I am all for changing it.

**Comment by eclarizio** [comment]
@epwinchell I don't know if there was any big rationale for styling them the way they are now, maybe that was just the "bootstrap" style back when we started using it? I'm not sure 😢 . I agree with  @chalettu though, I'm not against changing it to however it should be done to be standard with patternfly.

**Comment by Rohoover** [comment]
From an accessibility standpoint they're pretty nightmarish for those with visual impairment. 

+1 to switch to PF

**Comment by terezanovotna** [comment]
+1 to switch to PF [radio button](https://www.patternfly.org/pattern-library/forms-and-controls/data-input/)

**Comment by himdel** [comment]
+1 too, but whoever ends up doing it, please fix this in all the places, there's at least 2 - dialog-editor & dialog-user
