### ISSUE TITLE
Refreshing forms on update from Automate

### ISSUE THREAD

**Issue by romanblanco** [ManageIQ/ui-components#396]
While updating service dialogs by values from automate, the validation does not get updated automatically. After hover action, the Submit button gets enabled:

![Screencast from 2019-06-24 12-43-45](https://user-images.githubusercontent.com/1187051/60019717-14c4d380-967e-11e9-9ef7-2ce73f92eac0.gif)

**Comment by martinpovolny** [comment]
@eclarizio : and this one, please ;-)

**Comment by himdel** [comment]
Note to self: this may be fixed in https://github.com/ManageIQ/ui-components/pull/399

(because `DialogField.$onInit` now does `validateField` by default)

**Comment by himdel** [comment]
Fixed in #396, the whole refresh path never really ran the setupField conversions, now it does.
