### ISSUE TITLE
Prefer CSS classes over inline styles

### ISSUE THREAD

**Issue by himdel** [ManageIQ/ui-components#40]
We do have a bunch of inline style declarations that we probably want in CSS instead.

Just so as not to forget, raised in https://github.com/ManageIQ/ui-components/pull/37 .

**Comment by chriskacerguis** [comment]
@AllenBW no rush, but if you get a few cycles...could you please do this?

**Comment by AllenBW** [comment]
@chriskacerguis what? don't understand.

**Comment by chriskacerguis** [comment]
@AllenBW based on what @himdel stated, it seems to indicate that there are lots of instances of inline styles, and those should be moved into CSS files.  At some point it would be nice to address those and close the ticket.  Make sense?

**Comment by AllenBW** [comment]
@chriskacerguis as i understand it, [🔪 these?](https://github.com/ManageIQ/ui-components/search?l=HTML&q=+style%3D&type=&utf8=✓)

**Comment by himdel** [comment]
@miq-bot remove_label stale

This is still present.

And yes, @AllenBW, those :)
