### ISSUE TITLE
Broken dropdown with items number in table

### ISSUE THREAD

**Issue by bekasovoleg** [ManageIQ/ui-components#416]
Has anyone had such bug? I have this bug when try to use `miq-data-table` in `manageiq-ui-service`
 
![Screenshot from 2019-09-13 18-10-01](https://user-images.githubusercontent.com/14850567/64873542-f7d2e780-d651-11e9-9f35-41eb76748a0b.png)

**Comment by bekasovoleg** [comment]
I figure out there is no `dropdown-menu` class when I use `miq-data-table`
![Screenshot from 2019-09-13 18-18-41](https://user-images.githubusercontent.com/14850567/64874061-fce46680-d652-11e9-8a55-1e20e38a37db.png)

But there is `dropdown-menu` class in `ui-components` Demo

![Screenshot from 2019-09-13 18-15-42](https://user-images.githubusercontent.com/14850567/64873808-8ba4b380-d652-11e9-8709-82f5d47bfc22.png)

**Comment by himdel** [comment]
Fixed by #418, I believe :)

**Comment by himdel** [comment]
> when try to use miq-data-table in manageiq-ui-service

@bekasovoleg side note, we're trying to move off angular (in all the manageiq projects) to reduce the number of frameworks to ideally 1.

So, if you're writing new code, please consider writing it in react now.

As of https://github.com/ManageIQ/manageiq-ui-service/pull/1576, you *can* use react components in ui-service angular screens.

If you need the full GTL, you're out of luck, we don't have a full react implementation *yet*,
but we do have a [SimpleTable](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/javascript/components/simple-table/simple-table.jsx) component for just a table,
and a [ReportDataTable](https://github.com/ManageIQ/manageiq-ui-classic/blob/master/app/javascript/components/report-data-table.jsx) component which is a gtl-like table with a paginator.

**Comment by bekasovoleg** [comment]
@himdel it would be great to move `ReportDataTable` to https://github.com/ManageIQ/react-ui-components

**Comment by martinpovolny** [comment]
> @himdel it would be great to move ReportDataTable to https://github.com/ManageIQ/react-ui-components

It talks directly to the `API`. So it depends on manageiq-ui-classic.

Why would you want to move it there?
