### ISSUE TITLE
miq-data-table pagination confused behavior

### ISSUE THREAD

**Issue by bekasovoleg** [ManageIQ/ui-components#419]
`miq-pagination` consists of `miq-sort-items`, `miq-paging` and `select all` checkbox

when `paginationCtrl.settings.hideSelect` is set, `miq-pagination` is hidden instead of only `select all` checkbox part

https://github.com/ManageIQ/ui-components/blob/master/src/gtl/components/pagination/pagination.html#L1

if `tableCtrl.settings.sortBy` isn't true, also `miq-pagination` is hidden instead of  `miq-sort-items` part

it checks here
https://github.com/ManageIQ/ui-components/blob/master/src/gtl/components/data-table/data-table.html#L4

we need to check  `tableCtrl.settings.sortBy`  only here:
https://github.com/ManageIQ/ui-components/blob/master/src/gtl/components/pagination/pagination.html#L18

also pagination isn't hidden, when `settings.isLoading == true`
https://github.com/ManageIQ/ui-components/blob/master/src/gtl/components/data-table/data-table.html#L4

**Comment by martinpovolny** [comment]
@bekasovoleg : we are going to rewrite this component in react in the following months.

I suggest you you make a list of issues/improvements and we apply it to the new (React) version.

**Comment by bekasovoleg** [comment]
@martinpovolny 

- Capability to disable column with select boxes
- Capability to hide columns
- Capability to show pagination on top and (or) bottom of table
- Filtering by column
- Capability to highlight certain rows

**Comment by himdel** [comment]
Closing, https://github.com/ManageIQ/manageiq-ui-classic/pull/7188 changed the implementation to react.
