### ISSUE TITLE
miq-data-table enhancement

### ISSUE THREAD

**Issue by bekasovoleg** [ManageIQ/ui-components#420]
Add capability to disable table cols:

```
cols: [
  {
    header_text: 'col1',
    col_idx: 1,
    hidden: true // cols with such option won't be shown
  },
  {
    header_text: 'col1',
    col_idx: 1,
    hidden: true
  }
]
```

First column uses for select box, but if we don't use select box, first column still is shown
We have no way to disable first column

Add check if there are select boxes

https://github.com/ManageIQ/ui-components/blob/master/src/gtl/components/data-table/data-table.html#L17

**Comment by himdel** [comment]
(closing, this is already part of the list in https://github.com/ManageIQ/ui-components/issues/419)
