### ISSUE TITLE
Address npm dependency issues found in master branch [Opened by bitHound]

### ISSUE THREAD

**Issue by mtho11** [ManageIQ/ui-components#45]
<p>bitHound discovered:</p> <ul> <li>4 packages with at least one security vulnerability.</li> <li>9 outdated packages.</li> </ul> <p>For details go to <a href="https://www.bithound.io/github/ManageIQ/ui-components/master/dependencies/npm">bitHound</a>.</p> 
***
Looks like we need to do some updating here. I don't mind doing the PR if no one else has the time.

**Comment by chriskacerguis** [comment]
@martinpovolny @himdel thoughts on doing a dependency update (as much as we can without breaking things?)

/cc @chalettu

**Comment by himdel** [comment]
"Opened by bitHound" and went stale .. just closing.

We will have to take a look at the npm dependencies when moving ui-classic to use ui-components via npm anyway.
