### ISSUE TITLE
Typedoc for Documentation?

### ISSUE THREAD

**Issue by mtho11** [ManageIQ/ui-components#49]
We might want to think about using [Typedoc](http://typedoc.org/) for our typescript documentation.

Here is sample of a project using it: http://molecuel.github.io/mlcl_core/classes/mlclcore.html#subjects

wdyt?

CC @karelhala @himdel @martinpovolny

**Comment by himdel** [comment]
Well, frankly, we may want to think about *having* a documentation :).

But idk, for me, I'm very much not a fan of javadoc-style documentation, nor cluttering the code with such comments.

I'd much prefer having clear code, and a handwritten doc for each component.

That said, whoever ends up actually writing the docs should have more say :)

**Comment by mtho11** [comment]
@himdel yeah, I'd be fine with no java-doc and actual documentation that is more useful. I see what you mean about it looking cluttered.
