### ISSUE TITLE
When running application typings error occure

### ISSUE THREAD

**Issue by karelhala** [ManageIQ/ui-components#53]
This is placeholder issue for someone who is not involved in merge process, we have abandoned typings package in https://github.com/ManageIQ/ui-components/pull/41 so if you had installed this package before this transition. Remove folder `typings` and `node_modules` and re-run `npm install` to check types from npm.

**Comment by mtho11** [comment]
@karelhala do we still need this issue now?

**Comment by chriskacerguis** [comment]
@karelhala following up with what @mtho11 asked...do we still need this issue now?

**Comment by karelhala** [comment]
@chriskacerguis not anymore, closing it.
