### ISSUE TITLE
"Multiselect" DropDown does not work in SUI

### ISSUE THREAD

**Issue by ITD27M01** [ManageIQ/ui-components#65]
Hi guys.
The "multiselect" options for DropDown list does not work in SUI. I cannot select multiple values for this type of element form SUI but can do it from classic ui:
Screen frim Classic UI:
![image](https://cloud.githubusercontent.com/assets/3703483/25244153/41fef4c2-2608-11e7-8642-c4b7598d4651.png)
Screen from SUI:
![image](https://cloud.githubusercontent.com/assets/3703483/25244170/4f77383a-2608-11e7-932e-f9dfe5b11495.png)
 Service have dynamic dialog with dropdown element with "multiselect" option:
![image](https://cloud.githubusercontent.com/assets/3703483/25244301/c8cce09a-2608-11e7-9b04-7fb82f9955fa.png)

**Comment by chriskacerguis** [comment]
@AllenBW could you take a look?

**Comment by AllenBW** [comment]
@ITD27M01 what version are you running?

**Comment by ITD27M01** [comment]
@chriskacerguis @AllenBW 
Hi Guys.
From the screenshots it is an euwe-1 or euwe-2 but currently I do not use SUI and I use CloudFroms (5.7.3) with subscription and I use Tech Support for BZ creation (this workflow speeds up the bug fixing for me)

**Comment by chriskacerguis** [comment]
@ITD27M01 ok, going to close this issue then :)
