### ISSUE TITLE
"warning fsevents@1.1.2: The platform "linux" is incompatible with this module."

### ISSUE THREAD

**Issue by abonas** [ManageIQ/ui-components#80]
here's the outcome of compiling - on Fedora 24:

- I get this warning on incompatibility:
"warning fsevents@1.1.2: The platform "linux" is incompatible with this module."
given that miq is running on linux - sounds like this warning should be resolved

**Comment by mtho11** [comment]
@abonas to be complete, I guess we would also need to know the node version and yarn version as well.
`node --version` and `yarn --version`

**Comment by mtho11** [comment]
Some hints... https://github.com/yarnpkg/yarn/issues/1285

**Comment by abonas** [comment]
node v 4.7.3
yarn v 0.24.5

**Comment by mtho11** [comment]
@abonas could you please try using node v6.x as that is the current active release and what is required for ui-components (https://github.com/ManageIQ/ui-components#development-environment). v4 is in [maintenance mode](https://github.com/nodejs/LTS)
