### ISSUE TITLE
bower-dev builds not working

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/ui-components#88]
Continuing from @himdel's comment: https://github.com/ManageIQ/ui-components/pull/83#issuecomment-315326029

> So.. I've updated the script to output $? after commit and push, just to verify the push isn't succeeding somewhere.. but I'm pretty much stumped. As in, can't continue without seeing the actual error message from git push.. @Fryguy I think you'll have to look into this, sorry :).
> 
> The script works, both on travis and locally, if I run the same with --dry-run and my credentials, the push pretends to succeed, so .. possibly a wrong GITHUB_AUTH value, or wrong syntax, or a leading/trailing space in the value or something like that...

See https://travis-ci.org/ManageIQ/ui-components#L966-L1114 as an example

cc @skateman

**Comment by Fryguy** [comment]
Additionally, I think we need a .gitignore on the bower-dev branch to ignore coverage and node_modules directory.  I also see more files in dist that are listed an untracked that we should handle somehow.

Even so, none of this should affect the git push.

**Comment by Fryguy** [comment]
I googled for git push exit code 128, and one interesting thing was https://stackoverflow.com/a/17228373, which *might* be relevant.

**Comment by chriskacerguis** [comment]
@chalettu could you please take a look here?

**Comment by himdel** [comment]
Well, I guess we can close since it is working now :)
