### ISSUE TITLE
Field error messages should be below input fields in the new dialog component

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/ui-components#94]
Please move the field error message below input fields on the new dialog component recently contributed in [PR#82](https://github.com/ManageIQ/ui-components/pull/82).

Below is a screenshot of the current implementation:
![Uploading Screen Shot 2017-07-26 at 12.42.18 PM.png…]()

Based on the [PF guidelines](http://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation/), "Text input fields with validation errors are indicated with a red border around the input box and a Field Error Message below the field describing the error."

**Comment by chalettu** [comment]
@serenamarie125 , I took your feedback on that and implemented it as part of PR #82 .   I tagged you in the updated screen interaction.

**Comment by chalettu** [comment]
![error_messages](https://user-images.githubusercontent.com/230549/28633799-354c87f4-71f2-11e7-8d0d-5ab3429a0441.gif)
For reference, here is the implementation that got merged.

**Comment by serenamarie125** [comment]
oh snap, i missed that!  Looks so much better, thank you @chalettu .  I'm cool with you closing this, sorry bout the mixup.
