### ISSUE TITLE
Dialog Editor common component should reflect the latest UX Designs

### ISSUE THREAD

**Issue by serenamarie125** [ManageIQ/ui-components#98]
Dialog Editor common component should reflect the latest UX Designs

Design work for the dialog editor can be found here: https://manageiq.github.io/manageiq-design/UX/ui-service/designer/Dialogs/design

When the dialog editor was part of the Service Designer, I think that Dave Taylor made many of the updates, unsure if they have been folded into the common component

@Loicavenel FYI

**Comment by romanblanco** [comment]
@serenamarie125 @himdel I believe we can close this
